[general]
title = "My Blog"
description = "A personal blog about technology and programming."
base_url = "https://myblog.com"

[theme]
theme_type = "preset"
preset = "catppuccin"

[images]
# quality = 25
compress_to_webp = true